import Head from 'next/head'

import Jobs from '../components/Jobs'

const Home = ({ data }) => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>Home Page</div>
        <Jobs jobs={data} />
      </main>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/posts?_page=1&_limit=10`
  )
  const data = await res.json()

  if (!data) {
    return {
      notFound: true,
    }
  }

  return {
    props: { data },
  }
}

// Home.layout = 'MainLayout'

export default Home
