import Head from 'next/head'
import Link from 'next/link'

// import { useRouter } from 'next/router'

const Jobs = ({ data }) => {
  // console.log(data)
  // const router = useRouter()
  // const { id } = router.query
  // console.log(id)

  return (
    <>
      <Head>
        <title>Job Detail : {data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <Link href="/">
            <a>{'<-'} Home</a>
          </Link>
        </div>
        <br />
        <div>{data.id}</div>
        <br />
        <div>{data.title}</div>
        <br />
        <div>{data.body}</div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const { params, res } = context
  const { id } = params

  const getJob = await fetch(`https://jsonplaceholder.typicode.com/posts/${id}`)
  const data = await getJob.json()

  if (getJob.ok) {
    return { props: { data } }
  }

  if (res) {
    res.writeHead(301, { Location: '/' }).end()
  }
}

Jobs.layout = 'JobLayout'

export default Jobs
